image: Visual Studio 2017

platform:
  - x86
  
configuration:
  - Release

install:
  - ps: .appveyor/install-vsix.ps1
  
build_script:
  - MSBuild "C:\projects\ownclouduniversal\src\OwncloudUniversal.sln" /t:Build /p:Configuration=Release;Platform="ARM";OutDir="C:\projects\ownclouduniversal\Release";AppxBundle=Always;AppxBundlePlatforms="x86|x64|ARM" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  
before_build:
  - nuget restore src/OwncloudUniversal.sln
  
artifacts:
  - path: Release\OwncloudUniversal\AppPackages
    name: OwncloudUniversal-Latest